[2025-10-12T07:52:17.090+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-12T07:52:17.104+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_sqlite_db.read_customers manual__2025-10-12T07:52:14.683148+00:00 [queued]>
[2025-10-12T07:52:17.112+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_sqlite_db.read_customers manual__2025-10-12T07:52:14.683148+00:00 [queued]>
[2025-10-12T07:52:17.113+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-10-12T07:52:17.136+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): read_customers> on 2025-10-12 07:52:14.683148+00:00
[2025-10-12T07:52:17.139+0000] {standard_task_runner.py:72} INFO - Started process 51 to run task
[2025-10-12T07:52:17.142+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'read_sqlite_db', 'read_customers', 'manual__2025-10-12T07:52:14.683148+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/read_sqlite_db.py', '--cfg-path', '/tmp/tmpi5s3f0_t']
[2025-10-12T07:52:17.144+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask read_customers
[2025-10-12T07:52:17.173+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-12T07:52:17.219+0000] {task_command.py:467} INFO - Running <TaskInstance: read_sqlite_db.read_customers manual__2025-10-12T07:52:14.683148+00:00 [running]> on host 3eeb3e8ab23c
[2025-10-12T07:52:17.315+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='read_sqlite_db' AIRFLOW_CTX_TASK_ID='read_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-10-12T07:52:14.683148+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-12T07:52:14.683148+00:00'
[2025-10-12T07:52:17.316+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-12T07:52:17.347+0000] {logging_mixin.py:190} INFO - ⚠️ No data found in 'test2' table.
[2025-10-12T07:52:17.347+0000] {python.py:240} INFO - Done. Returned value was: []
[2025-10-12T07:52:17.376+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-12T07:52:17.377+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=read_sqlite_db, task_id=read_customers, run_id=manual__2025-10-12T07:52:14.683148+00:00, execution_date=20251012T075214, start_date=20251012T075217, end_date=20251012T075217
[2025-10-12T07:52:17.436+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-12T07:52:17.451+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-12T07:52:17.453+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
